### ISSUE TITLE
[Story] Scan the repo for vulnerabilities with Trivy

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1799]
### As a user, I want

As a Developer, I want the code stored in Sage Monorepo to be scanned so that I know the vulnerabilities that may affect my contributions.

### Description

We are now using Trivy to scan the Docker images generated by Sage Monorepo. The reports open by Trivy does provide information about how to locate the project(s) affected by a vulnerability. However, I'm hoping that scanning the repo will enable Trivy to generate report that can point out the file where the fix should be implemented

### Have you linked this story to a GitHub Project?

- [X] I have linked this story to a GitHub Project and set its metadata.

**Comment by tschaffter** [comment]
This is the default configuration that would be generated when selecting Trivy as code scanning tool using GitHub UI:

```yaml
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: trivy

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '29 19 * * 4'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/my-organization/my-app:${{ github.sha }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

```
