### ISSUE TITLE
[Bug] Fix deployment of non-local OC API docs container

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#1926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What projects are you seeing the problem on?

OpenChallenges

### Current behavior

```yml
services:
  openchallenges-api-docs:
    image: ghcr.io/sage-bionetworks/openchallenges-api-docs:local
```

should be:

```yml
services:
  openchallenges-api-docs:
    image: ghcr.io/sage-bionetworks/openchallenges-api-docs:${OPENCHALLENGES_VERSION:-local}
```

### Commit ID

a4f2cfe6c71fe07a4477c35793f54408d2aa2ffa

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
