### ISSUE TITLE
[Feature] Create an ngrok profile for OC to run multiple tunnels with one session 

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2150]
### What product(s) is this feature for?

OpenChallenges

### Description

This could help us to open tunnel to OC apex (8000) and development server of OC app (4200)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
Create [config file](https://ngrok.com/docs/secure-tunnels/ngrok-agent/reference/config/): `~/.config/ngrok/ngrok.yml`

```yaml
version: "2"
authtoken: changeme
tunnels:
  openchallenges-apex:
    addr: 8000
    proto: http
  openchallenges-app:
    addr: 4200
    proto: http
```

Start the tunnels:

```console
ngrok start openchallenges-apex openchallenges-app
```
