### ISSUE TITLE
[Bug] Update Redocly and fix migration bugs for all projects

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2819]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

Sage Monorepo

### Current behavior

After updating to `@redocly/cli`, the following error is thrown when building the API docs for OC:

```bash
> nx run openchallenges-api-docs:build

> redocly build-docs --config redocly.yaml --output build/redoc-static.html

Found redocly.yaml and using theme.openapi options
Prerendering docs
TypeError: (0 , _react.useId) is not a function

Warning: command "redocly build-docs --config redocly.yaml --output build/redoc-static.html" exited with non-zero status code
```

This error is related to React, which I have removed a few days ago from the workspace dependencies in part to solve another issue encountered with Redocly. See #2797

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment]
Redolcy has React has a peer dependency:

```
  '@redocly/cli@1.25.2(encoding@0.1.13)(enzyme@3.11.0)':
    dependencies:
      '@redocly/openapi-core': 1.25.2(encoding@0.1.13)
      abort-controller: 3.0.0
      chokidar: 3.6.0
      colorette: 1.4.0
      core-js: 3.36.1
      form-data: 4.0.0
      get-port-please: 3.1.2
      glob: 7.2.3
      handlebars: 4.7.8
      mobx: 6.13.0
      node-fetch: 2.7.0(encoding@0.1.13)
      pluralize: 8.0.0
      react: 17.0.2
      react-dom: 17.0.2(react@17.0.2)
      redoc: 2.1.5(core-js@3.36.1)(encoding@0.1.13)(enzyme@3.11.0)(mobx@6.13.0)(react-dom@17.0.2(react@17.0.2))(react@17.0.2)(styled-components@6.1.13(react-dom@17.0.2(react@17.0.2))(react@17.0.2))
      semver: 7.6.2
      simple-websocket: 9.1.0
      styled-components: 6.1.13(react-dom@17.0.2(react@17.0.2))(react@17.0.2)
      yargs: 17.0.1
    transitivePeerDependencies:
      - bufferutil
      - encoding
      - enzyme
      - react-native
      - supports-color
      - utf-8-validate
```
